### ISSUE TITLE
Verbind niet met magister

### ISSUE THREAD

**Issue by coollorenzo** [Vogeltak/Magister-6-api#5]
Ik heb al de nodig libaries geïnstalleerd de code als zip gedownload en example.py gestart verder niks verandert en als ik mijn dan al mijn gegevens invul (ze zijn 100% goed) dan krijg ik de volgende error:
 
```
Traceback (most recent call last):
  File "F:\user\Magister-6-api-master\example.py", line 24, in <module>
    m = magister.Magister(school_prefix, username, password)
  File "F:\user\Magister-6-api-master\magister\magister.py", line 41, in __init__
    id = self.account_data["Persoon"]["Id"]
KeyError: 'Persoon'
```

Is dit een bug of doe ik iets fout?

**Comment by lieuwex** [comment]
@Vogeltak en ik hebben al een tijdje niet aan deze library gewerkt hoewel de Magister API wel meerdere malen ondertussen verandert is, het is dus een bug. Ik heb niet echt meer tijd/zin om aan deze lib te werken.

Ik kan niet spreken namens @Vogeltak natuurlijk.

Als je van plan bent zelf er naar te gaan kijken is [dit](https://github.com/Vogeltak/Magister-6-api/blob/master/magister/magister.py#L23) een goede plek om te starten, denk ik.

Als anderen talen dan Python ook een optie is raad ik je aan een andere library te zoeken, bijvoorbeeld uit [deze (misschien incomplete) lijst](https://github.com/DutchCodeGeeks/MagisterHub/blob/master/libs/Magister6.md)

**Comment by coollorenzo** [comment]
Ik ga er aan werken en als ik klaar ben stuur ik natuurlijk een pull request het lijkt er nu op dat het een probleem is met het inloggen.

**Comment by lieuwex** [comment]
:+1: :tada:

**Comment by coollorenzo** [comment]
Ik heb de bug van het inloggen gefixt maar er zijn nog wel andere bugs wat heb je liever dat ik nu een pullrequest stuur of als ik de rest van fouten ook heb gefixt?
