### ISSUE TITLE
No longer able to login

### ISSUE THREAD

**Issue by GitGozer** [Vogeltak/Magister-6-api#7]
I am no longer able to log in since a few days, this is the error I get:

`File "example.py", line 42, in __init__
     id = self.account_data["Persoon"]["Id"]
 KeyError: 'Persoon'`

I suspect that this has something to do with the new magister version but I don't know how to fix this since I can't find any documentation on magister's API.

**Comment by coollorenzo** [comment]
I'm working on it!

**Comment by GitGozer** [comment]
Great :D

**Comment by coollorenzo** [comment]
I fixed it now waiting for my pull request to get accepted
